// This file will be auto-generated by Supabase CLI after running migrations
// For now, we define the types manually based on our schema

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

// Enum types matching database
export type UserRole = 'super_admin' | 'admin' | 'manager' | 'staff' | 'vendor' | 'readonly'
export type TenantPlan = 'free' | 'starter' | 'professional' | 'enterprise'
export type TenantStatus = 'active' | 'suspended' | 'cancelled' | 'trial'
export type LocationStatus = 'active' | 'temporarily_closed' | 'permanently_closed'
export type AssetStatus = 'active' | 'under_maintenance' | 'retired' | 'transferred' | 'disposed'
export type TicketStatus = 'submitted' | 'in_progress' | 'completed' | 'closed' | 'rejected' | 'on_hold'
export type TicketPriority = 'low' | 'medium' | 'high' | 'critical'
export type ComplianceStatus = 'active' | 'expiring_soon' | 'expired' | 'pending_renewal' | 'conditional' | 'failed_inspection' | 'suspended'
export type InvoiceStatus = 'pending' | 'approved' | 'paid' | 'disputed'
export type IncidentStatus = 'active' | 'contained' | 'resolved'
export type IncidentSeverity = 'high' | 'critical'
export type PMFrequency = 'daily' | 'weekly' | 'biweekly' | 'monthly' | 'quarterly' | 'semi_annually' | 'annually'
export type NotificationChannel = 'email' | 'sms' | 'push' | 'slack'

export interface Database {
  public: {
    Tables: {
      tenants: {
        Row: {
          id: string
          name: string
          slug: string
          plan: TenantPlan
          status: TenantStatus
          trial_ends_at: string | null
          stripe_customer_id: string | null
          stripe_subscription_id: string | null
          max_users: number
          max_locations: number
          storage_limit_gb: number
          features: Json
          branding: Json
          custom_domain: string | null
          domain_verified_at: string | null
          owner_email: string
          billing_email: string | null
          phone: string | null
          address: string | null
          created_at: string
          updated_at: string
          deleted_at: string | null
        }
        Insert: {
          id?: string
          name: string
          slug: string
          plan?: TenantPlan
          status?: TenantStatus
          trial_ends_at?: string | null
          stripe_customer_id?: string | null
          stripe_subscription_id?: string | null
          max_users?: number
          max_locations?: number
          storage_limit_gb?: number
          features?: Json
          branding?: Json
          custom_domain?: string | null
          domain_verified_at?: string | null
          owner_email: string
          billing_email?: string | null
          phone?: string | null
          address?: string | null
          created_at?: string
          updated_at?: string
          deleted_at?: string | null
        }
        Update: {
          id?: string
          name?: string
          slug?: string
          plan?: TenantPlan
          status?: TenantStatus
          trial_ends_at?: string | null
          stripe_customer_id?: string | null
          stripe_subscription_id?: string | null
          max_users?: number
          max_locations?: number
          storage_limit_gb?: number
          features?: Json
          branding?: Json
          custom_domain?: string | null
          domain_verified_at?: string | null
          owner_email?: string
          billing_email?: string | null
          phone?: string | null
          address?: string | null
          created_at?: string
          updated_at?: string
          deleted_at?: string | null
        }
      }
      users: {
        Row: {
          id: string
          tenant_id: string
          auth_user_id: string | null
          email: string
          full_name: string
          role: UserRole
          phone: string | null
          location_id: string | null
          language_preference: 'en' | 'es'
          is_active: boolean
          must_set_password: boolean
          deactivated_at: string | null
          notification_preferences: Json
          created_at: string
          updated_at: string
          deleted_at: string | null
        }
        Insert: {
          id?: string
          tenant_id: string
          auth_user_id?: string | null
          email: string
          full_name: string
          role?: UserRole
          phone?: string | null
          location_id?: string | null
          language_preference?: 'en' | 'es'
          is_active?: boolean
          must_set_password?: boolean
          deactivated_at?: string | null
          notification_preferences?: Json
          created_at?: string
          updated_at?: string
          deleted_at?: string | null
        }
        Update: {
          id?: string
          tenant_id?: string
          auth_user_id?: string | null
          email?: string
          full_name?: string
          role?: UserRole
          phone?: string | null
          location_id?: string | null
          language_preference?: 'en' | 'es'
          is_active?: boolean
          must_set_password?: boolean
          deactivated_at?: string | null
          notification_preferences?: Json
          created_at?: string
          updated_at?: string
          deleted_at?: string | null
        }
      }
      tenant_invitations: {
        Row: {
          id: string
          tenant_id: string
          email: string
          role: UserRole
          invited_by: string | null
          token: string
          expires_at: string
          accepted_at: string | null
          location_id: string | null
          created_at: string
          deleted_at: string | null
        }
        Insert: {
          id?: string
          tenant_id: string
          email: string
          role: UserRole
          invited_by?: string | null
          token?: string
          expires_at?: string
          accepted_at?: string | null
          location_id?: string | null
          created_at?: string
          deleted_at?: string | null
        }
        Update: {
          id?: string
          tenant_id?: string
          email?: string
          role?: UserRole
          invited_by?: string | null
          token?: string
          expires_at?: string
          accepted_at?: string | null
          location_id?: string | null
          created_at?: string
          deleted_at?: string | null
        }
      }
      locations: {
        Row: {
          id: string
          tenant_id: string
          name: string
          brand: string | null
          address: string | null
          city: string | null
          state: string | null
          zip: string | null
          phone: string | null
          square_footage: number | null
          manager_id: string | null
          emergency_contact_phone: string | null
          status: LocationStatus
          opened_date: string | null
          closed_date: string | null
          created_at: string
          updated_at: string
          deleted_at: string | null
        }
        Insert: {
          id?: string
          tenant_id: string
          name: string
          brand?: string | null
          address?: string | null
          city?: string | null
          state?: string | null
          zip?: string | null
          phone?: string | null
          square_footage?: number | null
          manager_id?: string | null
          emergency_contact_phone?: string | null
          status?: LocationStatus
          opened_date?: string | null
          closed_date?: string | null
          created_at?: string
          updated_at?: string
          deleted_at?: string | null
        }
        Update: {
          id?: string
          tenant_id?: string
          name?: string
          brand?: string | null
          address?: string | null
          city?: string | null
          state?: string | null
          zip?: string | null
          phone?: string | null
          square_footage?: number | null
          manager_id?: string | null
          emergency_contact_phone?: string | null
          status?: LocationStatus
          opened_date?: string | null
          closed_date?: string | null
          created_at?: string
          updated_at?: string
          deleted_at?: string | null
        }
      }
      assets: {
        Row: {
          id: string
          tenant_id: string
          name: string
          category_id: string | null
          asset_type_id: string | null
          location_id: string | null
          serial_number: string | null
          model: string | null
          manufacturer: string | null
          purchase_date: string | null
          purchase_price: number | null
          warranty_expiration: string | null
          expected_lifespan_years: number | null
          vendor_id: string | null
          status: AssetStatus
          qr_code: string | null
          manual_url: string | null
          spec_sheet_path: string | null
          photo_path: string | null
          notes: string | null
          created_at: string
          updated_at: string
          deleted_at: string | null
        }
        Insert: {
          id?: string
          tenant_id: string
          name: string
          category_id?: string | null
          asset_type_id?: string | null
          location_id?: string | null
          serial_number?: string | null
          model?: string | null
          manufacturer?: string | null
          purchase_date?: string | null
          purchase_price?: number | null
          warranty_expiration?: string | null
          expected_lifespan_years?: number | null
          vendor_id?: string | null
          status?: AssetStatus
          qr_code?: string | null
          manual_url?: string | null
          spec_sheet_path?: string | null
          photo_path?: string | null
          notes?: string | null
          created_at?: string
          updated_at?: string
          deleted_at?: string | null
        }
        Update: {
          id?: string
          tenant_id?: string
          name?: string
          category_id?: string | null
          asset_type_id?: string | null
          location_id?: string | null
          serial_number?: string | null
          model?: string | null
          manufacturer?: string | null
          purchase_date?: string | null
          purchase_price?: number | null
          warranty_expiration?: string | null
          expected_lifespan_years?: number | null
          vendor_id?: string | null
          status?: AssetStatus
          qr_code?: string | null
          manual_url?: string | null
          spec_sheet_path?: string | null
          photo_path?: string | null
          notes?: string | null
          created_at?: string
          updated_at?: string
          deleted_at?: string | null
        }
      }
      asset_categories: {
        Row: {
          id: string
          tenant_id: string
          name: string
          description: string | null
          default_lifespan_years: number | null
          parent_category_id: string | null
          created_at: string
          deleted_at: string | null
        }
        Insert: {
          id?: string
          tenant_id: string
          name: string
          description?: string | null
          default_lifespan_years?: number | null
          parent_category_id?: string | null
          created_at?: string
          deleted_at?: string | null
        }
        Update: {
          id?: string
          tenant_id?: string
          name?: string
          description?: string | null
          default_lifespan_years?: number | null
          parent_category_id?: string | null
          created_at?: string
          deleted_at?: string | null
        }
      }
      vendors: {
        Row: {
          id: string
          tenant_id: string
          name: string
          contact_name: string | null
          email: string | null
          phone: string | null
          emergency_phone: string | null
          address: string | null
          service_categories: string[]
          is_preferred: boolean
          contract_start_date: string | null
          contract_expiration: string | null
          insurance_expiration: string | null
          insurance_minimum_required: number | null
          hourly_rate: number | null
          notes: string | null
          is_active: boolean
          created_at: string
          updated_at: string
          deleted_at: string | null
        }
        Insert: {
          id?: string
          tenant_id: string
          name: string
          contact_name?: string | null
          email?: string | null
          phone?: string | null
          emergency_phone?: string | null
          address?: string | null
          service_categories?: string[]
          is_preferred?: boolean
          contract_start_date?: string | null
          contract_expiration?: string | null
          insurance_expiration?: string | null
          insurance_minimum_required?: number | null
          hourly_rate?: number | null
          notes?: string | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
          deleted_at?: string | null
        }
        Update: {
          id?: string
          tenant_id?: string
          name?: string
          contact_name?: string | null
          email?: string | null
          phone?: string | null
          emergency_phone?: string | null
          address?: string | null
          service_categories?: string[]
          is_preferred?: boolean
          contract_start_date?: string | null
          contract_expiration?: string | null
          insurance_expiration?: string | null
          insurance_minimum_required?: number | null
          hourly_rate?: number | null
          notes?: string | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
          deleted_at?: string | null
        }
      }
      ticket_categories: {
        Row: {
          id: string
          tenant_id: string
          name: string
          name_es: string | null
          description: string | null
          default_priority: TicketPriority
          default_assignee_id: string | null
          preferred_vendor_id: string | null
          escalation_hours: number
          created_at: string
          deleted_at: string | null
        }
        Insert: {
          id?: string
          tenant_id: string
          name: string
          name_es?: string | null
          description?: string | null
          default_priority?: TicketPriority
          default_assignee_id?: string | null
          preferred_vendor_id?: string | null
          escalation_hours?: number
          created_at?: string
          deleted_at?: string | null
        }
        Update: {
          id?: string
          tenant_id?: string
          name?: string
          name_es?: string | null
          description?: string | null
          default_priority?: TicketPriority
          default_assignee_id?: string | null
          preferred_vendor_id?: string | null
          escalation_hours?: number
          created_at?: string
          deleted_at?: string | null
        }
      }
      tickets: {
        Row: {
          id: string
          tenant_id: string
          ticket_number: number
          title: string
          description: string | null
          category_id: string | null
          location_id: string | null
          asset_id: string | null
          priority: TicketPriority
          status: TicketStatus
          submitted_by: string | null
          assigned_to: string | null
          vendor_id: string | null
          parent_ticket_id: string | null
          related_ticket_ids: string[] | null
          merged_into_ticket_id: string | null
          is_duplicate: boolean
          estimated_cost: number | null
          actual_cost: number | null
          is_warranty_claim: boolean
          due_date: string | null
          started_at: string | null
          completed_at: string | null
          verified_at: string | null
          closed_at: string | null
          is_emergency: boolean
          contained_at: string | null
          resolution_notes: string | null
          created_at: string
          updated_at: string
          deleted_at: string | null
        }
        Insert: {
          id?: string
          tenant_id: string
          ticket_number: number
          title: string
          description?: string | null
          category_id?: string | null
          location_id?: string | null
          asset_id?: string | null
          priority?: TicketPriority
          status?: TicketStatus
          submitted_by?: string | null
          assigned_to?: string | null
          vendor_id?: string | null
          parent_ticket_id?: string | null
          related_ticket_ids?: string[] | null
          merged_into_ticket_id?: string | null
          is_duplicate?: boolean
          estimated_cost?: number | null
          actual_cost?: number | null
          is_warranty_claim?: boolean
          due_date?: string | null
          started_at?: string | null
          completed_at?: string | null
          verified_at?: string | null
          closed_at?: string | null
          is_emergency?: boolean
          contained_at?: string | null
          resolution_notes?: string | null
          created_at?: string
          updated_at?: string
          deleted_at?: string | null
        }
        Update: {
          id?: string
          tenant_id?: string
          ticket_number?: number
          title?: string
          description?: string | null
          category_id?: string | null
          location_id?: string | null
          asset_id?: string | null
          priority?: TicketPriority
          status?: TicketStatus
          submitted_by?: string | null
          assigned_to?: string | null
          vendor_id?: string | null
          parent_ticket_id?: string | null
          related_ticket_ids?: string[] | null
          merged_into_ticket_id?: string | null
          is_duplicate?: boolean
          estimated_cost?: number | null
          actual_cost?: number | null
          is_warranty_claim?: boolean
          due_date?: string | null
          started_at?: string | null
          completed_at?: string | null
          verified_at?: string | null
          closed_at?: string | null
          is_emergency?: boolean
          contained_at?: string | null
          resolution_notes?: string | null
          created_at?: string
          updated_at?: string
          deleted_at?: string | null
        }
      }
      compliance_documents: {
        Row: {
          id: string
          tenant_id: string
          name: string
          document_type_id: string | null
          location_id: string | null
          location_ids: string[] | null
          issue_date: string | null
          expiration_date: string | null
          issuing_authority: string | null
          document_number: string | null
          file_path: string | null
          status: ComplianceStatus
          is_conditional: boolean
          conditional_requirements: string | null
          conditional_deadline: string | null
          renewal_submitted_date: string | null
          renewal_cost: number | null
          renewal_assigned_to: string | null
          failed_inspection_date: string | null
          corrective_action_required: string | null
          reinspection_date: string | null
          notes: string | null
          created_at: string
          updated_at: string
          deleted_at: string | null
        }
        Insert: {
          id?: string
          tenant_id: string
          name: string
          document_type_id?: string | null
          location_id?: string | null
          location_ids?: string[] | null
          issue_date?: string | null
          expiration_date?: string | null
          issuing_authority?: string | null
          document_number?: string | null
          file_path?: string | null
          status?: ComplianceStatus
          is_conditional?: boolean
          conditional_requirements?: string | null
          conditional_deadline?: string | null
          renewal_submitted_date?: string | null
          renewal_cost?: number | null
          renewal_assigned_to?: string | null
          failed_inspection_date?: string | null
          corrective_action_required?: string | null
          reinspection_date?: string | null
          notes?: string | null
          created_at?: string
          updated_at?: string
          deleted_at?: string | null
        }
        Update: {
          id?: string
          tenant_id?: string
          name?: string
          document_type_id?: string | null
          location_id?: string | null
          location_ids?: string[] | null
          issue_date?: string | null
          expiration_date?: string | null
          issuing_authority?: string | null
          document_number?: string | null
          file_path?: string | null
          status?: ComplianceStatus
          is_conditional?: boolean
          conditional_requirements?: string | null
          conditional_deadline?: string | null
          renewal_submitted_date?: string | null
          renewal_cost?: number | null
          renewal_assigned_to?: string | null
          failed_inspection_date?: string | null
          corrective_action_required?: string | null
          reinspection_date?: string | null
          notes?: string | null
          created_at?: string
          updated_at?: string
          deleted_at?: string | null
        }
      }
      pm_schedules: {
        Row: {
          id: string
          tenant_id: string
          template_id: string | null
          name: string
          description: string | null
          asset_id: string | null
          location_id: string | null
          frequency: PMFrequency
          day_of_week: number | null
          day_of_month: number | null
          month_of_year: number | null
          assigned_to: string | null
          vendor_id: string | null
          estimated_cost: number | null
          is_active: boolean
          last_generated_at: string | null
          next_due_date: string | null
          created_at: string
          updated_at: string
          deleted_at: string | null
        }
        Insert: {
          id?: string
          tenant_id: string
          name: string
          template_id?: string | null
          description?: string | null
          asset_id?: string | null
          location_id?: string | null
          frequency?: PMFrequency
          day_of_week?: number | null
          day_of_month?: number | null
          month_of_year?: number | null
          assigned_to?: string | null
          vendor_id?: string | null
          estimated_cost?: number | null
          is_active?: boolean
          last_generated_at?: string | null
          next_due_date?: string | null
          created_at?: string
          updated_at?: string
          deleted_at?: string | null
        }
        Update: {
          id?: string
          tenant_id?: string
          template_id?: string | null
          name?: string
          description?: string | null
          asset_id?: string | null
          location_id?: string | null
          frequency?: PMFrequency
          day_of_week?: number | null
          day_of_month?: number | null
          month_of_year?: number | null
          assigned_to?: string | null
          vendor_id?: string | null
          estimated_cost?: number | null
          is_active?: boolean
          last_generated_at?: string | null
          next_due_date?: string | null
          created_at?: string
          updated_at?: string
          deleted_at?: string | null
        }
      }
      budgets: {
        Row: {
          id: string
          tenant_id: string
          location_id: string | null
          category: string | null
          fiscal_year: number
          annual_budget: number
          spent_amount: number
          notes: string | null
          created_at: string
          updated_at: string
          deleted_at: string | null
        }
        Insert: {
          id?: string
          tenant_id: string
          location_id?: string | null
          category?: string | null
          fiscal_year: number
          annual_budget?: number
          spent_amount?: number
          notes?: string | null
          created_at?: string
          updated_at?: string
          deleted_at?: string | null
        }
        Update: {
          id?: string
          tenant_id?: string
          location_id?: string | null
          category?: string | null
          fiscal_year?: number
          annual_budget?: number
          spent_amount?: number
          notes?: string | null
          created_at?: string
          updated_at?: string
          deleted_at?: string | null
        }
      }
      ticket_status_history: {
        Row: {
          id: string
          ticket_id: string | null
          from_status: TicketStatus | null
          to_status: TicketStatus
          changed_by: string | null
          notes: string | null
          created_at: string
        }
        Insert: {
          id?: string
          ticket_id?: string | null
          from_status?: TicketStatus | null
          to_status: TicketStatus
          changed_by?: string | null
          notes?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          ticket_id?: string | null
          from_status?: TicketStatus | null
          to_status?: TicketStatus
          changed_by?: string | null
          notes?: string | null
          created_at?: string
        }
      }
      ticket_comments: {
        Row: {
          id: string
          ticket_id: string | null
          user_id: string | null
          comment: string
          is_internal: boolean
          created_at: string
          deleted_at: string | null
        }
        Insert: {
          id?: string
          ticket_id?: string | null
          user_id?: string | null
          comment: string
          is_internal?: boolean
          created_at?: string
          deleted_at?: string | null
        }
        Update: {
          id?: string
          ticket_id?: string | null
          user_id?: string | null
          comment?: string
          is_internal?: boolean
          created_at?: string
          deleted_at?: string | null
        }
      }
      ticket_attachments: {
        Row: {
          id: string
          ticket_id: string | null
          file_path: string
          file_name: string
          file_type: string | null
          file_size_bytes: number | null
          uploaded_by: string | null
          attachment_type: string | null
          created_at: string
          deleted_at: string | null
        }
        Insert: {
          id?: string
          ticket_id?: string | null
          file_path: string
          file_name: string
          file_type?: string | null
          file_size_bytes?: number | null
          uploaded_by?: string | null
          attachment_type?: string | null
          created_at?: string
          deleted_at?: string | null
        }
        Update: {
          id?: string
          ticket_id?: string | null
          file_path?: string
          file_name?: string
          file_type?: string | null
          file_size_bytes?: number | null
          uploaded_by?: string | null
          attachment_type?: string | null
          created_at?: string
          deleted_at?: string | null
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      check_duplicate_ticket: {
        Args: {
          p_tenant_id: string
          p_location_id: string
          p_asset_id: string | null
          p_title: string
          p_hours_back: number
        }
        Returns: Database['public']['Tables']['tickets']['Row'][]
      }
      get_user_role: {
        Args: { user_id: string }
        Returns: UserRole
      }
      is_admin_or_above: {
        Args: { user_id: string }
        Returns: boolean
      }
    }
    Enums: {
      user_role: UserRole
      tenant_plan: TenantPlan
      tenant_status: TenantStatus
      location_status: LocationStatus
      asset_status: AssetStatus
      ticket_status: TicketStatus
      ticket_priority: TicketPriority
      compliance_status: ComplianceStatus
      invoice_status: InvoiceStatus
      incident_status: IncidentStatus
      incident_severity: IncidentSeverity
      pm_frequency: PMFrequency
      notification_channel: NotificationChannel
    }
  }
}

// Convenience type aliases
export type Tenant = Database['public']['Tables']['tenants']['Row']
export type User = Database['public']['Tables']['users']['Row']
export type Location = Database['public']['Tables']['locations']['Row']
export type Asset = Database['public']['Tables']['assets']['Row']
export type AssetCategory = Database['public']['Tables']['asset_categories']['Row']
export type Vendor = Database['public']['Tables']['vendors']['Row']
export type TicketCategory = Database['public']['Tables']['ticket_categories']['Row']
export type Ticket = Database['public']['Tables']['tickets']['Row']
export type ComplianceDocument = Database['public']['Tables']['compliance_documents']['Row']
export type PMSchedule = Database['public']['Tables']['pm_schedules']['Row']
export type Budget = Database['public']['Tables']['budgets']['Row']
